alarm: ETHERLINK_ETHERLINK_NETWORK_evm_health 
on: ETHERLINK_ETHERLINK_NETWORK.evm_applied_blueprints
lookup: sum -120s 
every: 15s 
crit: $this = 0
to: etherlink-ETHERLINK_NETWORK
info: No blueprints applied since 2 minutes for the EVM in ETHERLINK ETHERLINK_NETWORK.
