alarm: ETHERLINK_ETHERLINK_NETWORK_success_validated_blocks 
on: ETHERLINK_ETHERLINK_NETWORK.validated_blocks
lookup: sum -120s 
every: 15s 
crit: $this = 0
to: etherlink-ETHERLINK_NETWORK
info: No block successfully validated since 2 minutes for ETHERLINK ETHERLINK_NETWORK.
